### ISSUE TITLE
[QUESTION] SMTP-AUTH requested but missing secret phrase, message errors

### ISSUE THREAD

**Issue by akka2** [truemail-rb/truemail-rack#66]
### New issue checklist

- [x] I have updated `truemail-rack` to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/truemail-rb/truemail-rack/blob/master/CONTRIBUTING.md)
- [x] I have read the [documentation](https://truemail-rb.org/truemail-rack)
- [x] I have searched for [existing GitHub issues](https://github.com/truemail-rb/truemail-rack/issues)

### Issue description

We received this error when we try to check email address: 
##### Complete output when running truemail, including the stack trace and command used

```
{"date":"2021-12-21 16:43:15 +0100",

"email":"xxxxxx@gmail.com","

validation_type":"smtp",

"success":false,
"errors":{"smtp":"smtp error"},
"smtp_debug":[{"mail_host":"142.250.110.26","port_opened":true,
"connection":false,
"errors":{"connection":"SMTP-AUTH requested but missing secret phrase"}},

{"mail_host":"142.251.9.26","port_opened":true,
"connection":false,"errors":{"connection":"SMTP-AUTH requested but missing secret phrase"}},

{"mail_host":"142.250.150.26",
"port_opened":true,
"connection":false,
"errors":{"connection":"SMTP-AUTH requested but missing secret phrase"}},

{"mail_host":"74.125.200.27",
"port_opened":true,"connection":false,
"errors":{"connection":"SMTP-AUTH requested but missing secret phrase"}},

{"mail_host":"142.250.157.26",
"port_opened":true,
"connection":false,
"errors":{"connection":"SMTP-AUTH requested but missing secret phrase"}}],


"configuration":{"validation_type_by_domain":null,
"whitelist_validation":false,"whitelisted_domains":null,"blacklisted_domains":null,"blacklisted_mx_ip_addresses":null,"dns":null,"not_rfc_mx_lookup_flow":false,"smtp_fail_fast":false,"smtp_safe_check":false,"email_pattern":"default gem value","smtp_error_body_pattern":"default gem value"}}

```
<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by bestwebua** [comment]
Hi, @akka2! Looks like you have used not latest release. This bug have been fixed in `0.2.19`. Which version are you using?

Example from `truemail-rack 0.2.19`:
<img width="715" alt="Screenshot 2021-12-21 at 9 56 15 PM" src="https://user-images.githubusercontent.com/14002692/146989882-ad3b364b-8996-457e-9ffb-8ce87927242a.png">

**Comment by akka2** [comment]
Hi,  @bestwebua I have the last version installed but still get the error message, Thanks for your help 
![image](https://user-images.githubusercontent.com/78371420/147258984-5d105ad5-4582-454b-9702-3a5065314a33.png)

**Comment by bestwebua** [comment]
<img width="662" alt="Screenshot 2021-12-23 at 6 08 55 PM" src="https://user-images.githubusercontent.com/14002692/147265651-fb7c81df-afbe-4aa4-acbb-90d45f440abd.png">

<img width="665" alt="Screenshot 2021-12-23 at 6 09 35 PM" src="https://user-images.githubusercontent.com/14002692/147265737-9904dc81-a445-4fe7-bf75-a4dcb792c7dd.png">

Please provide output of these commands after execution in truemail server folder:
```
ruby -v
cat app/truemail_server/version.rb
```

**Comment by akka2** [comment]
hi, thanks for your feedback 
here is the output, i truemail rack version is installed 
![image](https://user-images.githubusercontent.com/78371420/147266401-72bda460-8b37-47b1-9dc4-49ab75315ea6.png)

**Comment by akka2** [comment]
![image](https://user-images.githubusercontent.com/78371420/147266614-2c6b030c-1619-4fe5-878b-db92bbed1df8.png)
version of the server

**Comment by bestwebua** [comment]
Stop the server, run `bundle clean --force` in truemail-rack folder, then `bundle install'. Which truemail version comes in log?

**Comment by akka2** [comment]
![image](https://user-images.githubusercontent.com/78371420/147271742-0f4a788d-0e4d-4f3c-80ce-5b97969de9a1.png)

**Comment by bestwebua** [comment]
```
cd root/truemail-rack
bundle clean --force
bundle install
VERIFIER_EMAIL=your_email@example.com ACCESS_TOKENS=token rackup
```

**Comment by akka2** [comment]
![image](https://user-images.githubusercontent.com/78371420/147277516-150ec99a-4854-4709-9175-aa9a57c0d302.png)
sorry mate

**Comment by bestwebua** [comment]
Which truemail version comes in log? What about another port?
```VERIFIER_EMAIL=your_email@example.com ACCESS_TOKENS=token rackup -p 2526```

**Comment by akka2** [comment]
here is the version : 
![image](https://user-images.githubusercontent.com/78371420/147278192-d3e4e60e-be42-4559-8e07-14999e01f7b7.png)

**Comment by akka2** [comment]
port 2526 : 
![image](https://user-images.githubusercontent.com/78371420/147278252-6a806ca7-9318-44cb-bd98-d1771fe554bf.png)

**Comment by bestwebua** [comment]
Ok, try to verify email through this serven instance running on 2526 port

**Comment by akka2** [comment]
how you do that ? change config.ru ?

**Comment by bestwebua** [comment]
Nope. Run server with `rackup -p 2526` and send http request to it `http localhost:9292 email==some_emain Authorization:token`

**Comment by akka2** [comment]
can I share my sever access  with you ? 
my email akkaouali@gmail.com

**Comment by bestwebua** [comment]
I have emailed you.

**Comment by bestwebua** [comment]
@akka2 It's rvm issue on your environment. In current config always uses previous version of truemail core.

**Comment by akka2** [comment]
@bestwebua ok, need an update ?

**Comment by bestwebua** [comment]
@akka2 Update for what? P.S.: checkout your email with details.

**Comment by bestwebua** [comment]
I have added to track version of running truemail server. It should help to debug, 'what are happening?', in cases like yours.

**Comment by akka2** [comment]
Cheers mate 
I appreciate your help
